import 'package:equatable/equatable.dart';

/// Product profitability entity showing how profitable a product is
class ProductProfitability extends Equatable {
  /// Product ID
  final String productId;

  /// Product name
  final String productName;

  /// Total profit generated by this product
  final double totalProfit;

  /// Total quantity sold
  final int totalSold;

  /// Average profit margin percentage
  final double averageMargin;

  const ProductProfitability({
    required this.productId,
    required this.productName,
    required this.totalProfit,
    required this.totalSold,
    required this.averageMargin,
  });

  /// Check if this is a profitable product
  bool get isProfitable => totalProfit > 0;

  /// Check if this is sold at a loss
  bool get isLoss => totalProfit < 0;

  /// Empty state for a product with no sales
  static ProductProfitability empty(String productId, String productName) =>
      ProductProfitability(
        productId: productId,
        productName: productName,
        totalProfit: 0,
        totalSold: 0,
        averageMargin: 0,
      );

  @override
  List<Object?> get props => [
        productId,
        productName,
        totalProfit,
        totalSold,
        averageMargin,
      ];
}
